import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from '../components/Links'

export default function Home() {
   return (
      <div className={styles.container}>
         <Head>
            <title>Sample Web</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className={styles.main}>
            <h1 className={styles.title}>
               Welcome to <a href="https://www.fazztrack.com/">fazztrack</a>
            </h1>

            <p className={styles.description}>
               login page &rarr;{' '}
               <Link to="/login">
                  <code className={styles.code}>localhost:3000/login</code>
               </Link>
            </p>

            <div className={styles.grid}>
               <a href="https://www.fazztrack.com/class/fullstack-mobile" className={styles.card}>
                  <h2>Fullstack Mobile &rarr;</h2>
                  <p>Belajar pengembangan aplikasi mobile</p>
               </a>

               <a href="https://www.fazztrack.com/class/fullstack-website" className={styles.card}>
                  <h2>Fullstack Website &rarr;</h2>
                  <p>Belajar pengembangan aplikasi web</p>
               </a>

               <a href="https://www.fazztrack.com/class/backend-devops" className={styles.card}>
                  <h2>Backend-Devops &rarr;</h2>
                  <p>Belajar membangun infrastruktur server</p>
               </a>

               <a href="https://www.fazztrack.com/FAQ" className={styles.card}>
                  <h2>Faq &rarr;</h2>
                  <p>Temukan jawaban dari pertanyaan anda</p>
               </a>
            </div>
         </main>

         <footer className={styles.footer}>
            <a
               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
               target="_blank"
               rel="noopener noreferrer"
            >
               Powered by{' '}
               <span className={styles.logo}>
                  <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
               </span>
            </a>
         </footer>
      </div>
   )
}
